#include <LiquidCrystal.h>
#include "linear.h"
#include "sensing.h"

//Macros
#define BLANK(num) ({unsigned int i;for(i=0; i<num; i++){lcd->print(" ");}})

//Globals
LiquidCrystal *lcd;
boolean locked=false;
Stats stats;

//Private prototypes
//differently from vanilla Arduino projects, those are needed, as the makefile
//used does not auto-generate the prototypes (thank god)
//also, the setup() and loop() functions *does not* need to be prototyped
void pinSetup();
void lcdSetup();
boolean statsOk(Stats stats); //returns true if stats are at safe levels
void readSensors(Stats *stats); //save readings on struct
void updateReadings(Stats *stats); //update readings on screen
void bias(boolean run); //enable/disable amplification bias
void warning(boolean run); //enable/disable warning on screen and bias cutoff 

//LCD messages and positions, considering 20x4 screen
#define TX_MSG  "TX" //Transmitting icon
#define TX_POSX 9
#define TX_POSY 3
#define WARNING_MSG "WARNING" //Harmful stats warning
#define WARNING_POSX  0  
#define WARNING_POSY  3
#define LOCKED_MSG "LOCKED" //Locked status
#define LOCKED_POSX 14
#define LOCKED_POSY 3

//Special symbols bitmap
byte degree_sign[8] = {
  B11100,
  B10100,
  B11100,
  B00000,
  B00000,
  B00000,
  B00000,
};

byte lock_sign[8] = {
  B00100,
  B01010,
  B10001,
  B11111,
  B11111,
  B11011,
  B11111,
};

//Arduino framework functions 
//main() is auto-generated by the makefile and calls main() once and loop()
//repeteadly, just as vanilla Arduino projects
void setup() {
  pinSetup();
  lcdSetup();
}

void loop() {
  return;
  readSensors(&stats); 
  if(statsOk(&stats)){
    warning(false);
    if(!locked && digitalRead(YTX_PIN))
      bias(true);
    else
      bias(false);
  }else{
    warning(true);  
    locked=true;
  }
  
  lcd->setCursor(LOCKED_POSX, LOCKED_POSY);
  if(locked)
    lcd->print(LOCKED_MSG);
  else
    BLANK(sizeof(LOCKED_MSG));  
  
  updateReadings(&stats);
}

void pinSetup(){    
  pinMode(RELAY80_PIN, OUTPUT);
  pinMode(RELAY40_PIN, OUTPUT);
  pinMode(RELAY20_PIN, OUTPUT);
  pinMode(RELAY10_PIN, OUTPUT);
  pinMode(BIAS_PIN, OUTPUT);  
  pinMode(BANDSW_PIN, INPUT_PULLUP);
  pinMode(REARM_PIN, INPUT_PULLUP);
  pinMode(YD0_PIN, INPUT);
  pinMode(YD1_PIN, INPUT);
  pinMode(YD2_PIN, INPUT);
  pinMode(YD3_PIN, INPUT);
}

void lcdSetup(){
  lcd = new LiquidCrystal(LCDR_PIN, LCDE_PIN, LCD4_PIN, LCD5_PIN, LCD6_PIN, LCD7_PIN);
  lcd->begin(20, 4); //AGM-2004D-201 has 20 rows and 4 lines
  lcd->createChar(0, degree_sign);
  lcd->createChar(1, lock_sign);
  
  lcd->setCursor(0, 0);
  lcd->print("BAND=");
  lcd->setCursor(0, 1);
  lcd->print("SWR=");
  lcd->setCursor(8, 1);
  lcd->print(":1");
  lcd->setCursor(13,1);
  lcd->print("T=");
  lcd->setCursor(18,1);
  lcd->write(byte(0));
  lcd->print("C");
  lcd->setCursor(0 ,2);
  lcd->print("P.IN=");
  lcd->setCursor(8, 2);
  lcd->print("W");
  lcd->setCursor(10,2);
  lcd->print("P.OUT="); 
  lcd->setCursor(19,2);
  lcd->print("W");
  /*
  lcd->setCursor(5, 0);
  lcd->print("20m/15m");
  lcd->setCursor(4, 1);
  lcd->print("1.50");
  lcd->setCursor(15, 1);
  lcd->print("100");
  lcd->setCursor(5, 2);
  lcd->print(" 90");
  lcd->setCursor(16,2);
  lcd->print("900");
  lcd->setCursor(0, 3);
  lcd->print("WARNING  TX  ");
  lcd->write(byte(1));
  lcd->print("LOCKED");
  */
}

void bias(boolean run){
  if(run){
    digitalWrite(BIAS_PIN, HIGH); 
    lcd->setCursor(TX_POSX, TX_POSY);           
    lcd->print(TX_MSG);
  }else{
    digitalWrite(BIAS_PIN, LOW);
    lcd->setCursor(TX_POSX, TX_POSY);            
    BLANK(sizeof(TX_MSG));
  }
}

void warning(boolean run){
  if(run){
    bias(false);
    lcd->setCursor(WARNING_POSX, WARNING_POSY);
    lcd->print(WARNING_MSG);
  }else{
    lcd->setCursor(WARNING_POSX, WARNING_POSY);
    BLANK(sizeof(WARNING_MSG));
  }
}

