ALTERNATE_CORE_PATH = mega32
BOARD_TAG = mega32-10
ISP_PORT = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER = stk500v1
AVRDUDE_ARD_BAUDRATE = 19200
AVRDUDE_OPTS = -v
ARDUINO_LIBS = LiquidCrystal

include Arduino.mk

